### ISSUE TITLE
как пролезть в любой приват

### ISSUE THREAD

**Issue by 008** [gamerforEA/GraviSuite-FakePlayers#1]
заснял на видео как можно с модом Гравсюит (твои ивенты) пролезть в любой приват. Лазать в текстурах https://youtu.be/358C8S_Tb40
Почини пожалуйста :)

**Comment by gamerforEA** [comment]
Это ошибка не мода, а ядра, так что ничем не могу помочь.

**Comment by 008** [comment]
а можно починить ломание стекляных панелек ? Просто ломает даже в привате и все тут.
