### ISSUE TITLE
Crash when switching a AdvDrill

### ISSUE THREAD

**Issue by friksasha** [gamerforEA/GraviSuite-FakePlayers#4]
Ну что сказать. Падает и всё тут. Пойду дальше копировать.

**Comment by friksasha** [comment]
"У меня озарение?"
Я думаю почему так много крашей, а может быть эта версия не для клиента? Может она подходит только для bukkit сервера и когда minecraft натыкается на EventHelper, то он ничего не может с ним сделать и возвращает ничего. Я пока не буду открывать новые issues, а подожду ответа автора.
Пойду у себя поправлю чтобы можно было играть в самом minecraft.

**Comment by gamerforEA** [comment]
Да, эта версия не для клиента. Впрочем, в релизах теперь поставляется поправленный клиентский мод.
slowpoke.jpg
